global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "/etc/prometheus/rules/*.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'sample-app'
    static_configs:
      - targets: ['sample-app:8080']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  - job_name: 'tempo'
    static_configs:
      - targets: ['tempo:3200']

  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']

  - job_name: 'pyroscope'
    static_configs:
      - targets: ['pyroscope:4040']